[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[fluffychat]
source = "github"
github = "krille-chan/fluffychat"
use_latest_release = true

[gpsrider]
source = "github"
github = "RomanK2311/GPSRider"

[llama_cpp]
source = "github"
github = "ggml-org/llama.cpp"
use_latest_release = true

[nchat]
source = "github"
github = "d99kris/nchat"
use_latest_release = true

[openeuicc]
source = "gitea"
gitea = "PeterCxy/OpenEUICC"
host = "gitea.angry.im"
use_max_tag = true

[stable-diffusion_cpp]
source = "github"
github = "leejet/stable-diffusion.cpp"
use_latest_release = true

[whisper_cpp]
source = "github"
github = "ggml-org/whisper.cpp"
use_latest_release = true
