name: Build OpenEUICC

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  process-tag-name:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.process-tag-name.outputs.semver }}
    steps:
      - name: Process Version for No v Prefix
        id: process-tag-name
        shell: python
        run: |
          import subprocess
          version = "${{ inputs.version }}"
          semver = version.replace("unpriv-", "")
          subprocess.run(f'echo semver={semver} >> $GITHUB_OUTPUT', shell=True, check=True)
  build:
    needs: process-tag-name
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v6
        with:
          repository: estkme-group/openeuicc
          submodules: recursive
          ref: ${{ inputs.version }}

      - name: Decode Secret Signing Configuration
        run: |
          echo "${{ secrets.OPENEUICC_SIGNING_KEY_JKS }}" | base64 -d > keystore.jks
          sudo mkdir -p /keystore
          sudo mv keystore.jks /keystore/keystore.jks
          echo "${{ secrets.OPENEUICC_SIGNING_CONFIG }}" | base64 -d > keystore.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release
        run: ./gradlew --no-daemon assembleRelease :app:assembleReleaseMagiskModuleDir

      - name: Prepare Release Assets
        run: |
          SAVE_DIR=$(pwd)
          cd app/build/magisk/release
          zip -r $SAVE_DIR/Magisk-Module-OpenEUICC-${{ needs.process-tag-name.outputs.semver }}.zip ./*

      - name: Upload Magisk Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Magisk-Module-OpenEUICC-${{ needs.process-tag-name.outputs.semver }}
          compression-level: 0
          path: Magisk-Module-OpenEUICC-${{ needs.process-tag-name.outputs.semver }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: openeuicc-${{ needs.process-tag-name.outputs.semver }}
          name: Binary build for OpenEUICC Magisk Module (${{ needs.process-tag-name.outputs.semver }})
          body: |
            This release contains the magisk module of [OpenEUICC](https://gitea.angry.im/PeterCxy/OpenEUICC/).
          files: Magisk-Module-OpenEUICC-${{ needs.process-tag-name.outputs.semver }}.zip
          fail_on_unmatched_files: true
