name: Build OpenEUICC

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v6
        with:
          repository: estkme-group/openeuicc
          submodules: recursive
          ref: unpriv-${{ inputs.version }}
          fetch-depth: 0

      - name: Decode Secret Signing Configuration
        run: |
          echo "${{ secrets.OPENEUICC_SIGNING_KEY_JKS }}" | base64 -d > keystore.jks
          sudo mkdir -p /keystore
          sudo mv keystore.jks /keystore/keystore.jks
          echo "${{ secrets.OPENEUICC_SIGNING_CONFIG }}" | base64 -d > keystore.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release
        run: ./gradlew --no-daemon assembleRelease :app:assembleReleaseMagiskModuleDir

      - name: Prepare Release Assets
        run: |
          SAVE_DIR=$(pwd)
          cd app/build/magisk/release
          zip -r $SAVE_DIR/Magisk-Module-OpenEUICC-${{ inputs.version }}.zip ./*

      - name: Upload Magisk Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Magisk-Module-OpenEUICC-${{ inputs.version }}
          compression-level: 0
          path: Magisk-Module-OpenEUICC-${{ inputs.version }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: openeuicc-${{ inputs.version }}
          name: Binary build for OpenEUICC Magisk Module (${{ inputs.version }})
          body: |
            This release contains the magisk module of [OpenEUICC](https://gitea.angry.im/PeterCxy/OpenEUICC/).
          files: Magisk-Module-OpenEUICC-${{ inputs.version }}.zip
          fail_on_unmatched_files: true